name: shared_provider
description: "Shared instance provider package"
version: 0.0.1
repository: https://github.com/dadagov125/shared_provider

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
